export { M as MAT_BUTTON_CONFIG, f as MAT_FAB_DEFAULT_OPTIONS, g as MAT_FAB_DEFAULT_OPTIONS_FACTORY, d as MatAnchor, c as MatButton, a as MatButtonAppearance, b as MatButtonConfig, n as MatButtonModule, j as MatFabAnchor, h as MatFabButton, e as MatFabDefaultOptions, m as MatIconAnchor, l as MatIconButton, k as MatMiniFabAnchor, i as MatMiniFabButton } from '../module.d-d86ca350.js';
import '@angular/core';
import '../common-module.d-0e6515ae.js';
import '@angular/cdk/bidi';
import '../index.d-cc6e48d4.js';
import '../ripple.d-f2cd74cf.js';
import '@angular/cdk/platform';
import '@angular/cdk/a11y';
import '../palette.d-ec4a617c.js';
import '../ripple-loader.d-e5ac6c14.js';
